# Generated by Django 3.2.9 on 2022-08-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booked',
            new_name='Booking',
        ),
    ]
